version: '3'

services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    environment:
      # 时区上海
      TZ: Asia/Shanghai
      # root 密码
      MYSQL_ROOT_PASSWORD: crush123
      # 初始化数据库
      MYSQL_DATABASE: crush-cloud
    ports:
      - "3306:3306"
    volumes:
      # 数据挂载
      - /Users/lc/dataCenter/docker/mysql/data/:/var/lib/mysql/
      # 配置挂载
      - /Users/lc/dataCenter/docker/mysql/conf/:/etc/mysql/conf.d/
    command:
      # 将mysql8.0默认密码策略 修改为 原先 策略 (mysql8.0对其默认策略做了更改 会导致密码无法匹配)
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
    privileged: true

  redis:
    image: redis:6.2.7
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    volumes:
      # 配置文件
      - /Users/lc/dataCenter/docker/redis/conf:/redis/config
      # 数据文件
      - /Users/lc/dataCenter/docker/redis/data/:/redis/data/
    command: "redis-server /redis/config/redis.conf"
    privileged: true

  nginx-web:
    image: nginx:1.22.1
    container_name: nginx-web
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # 证书映射
      - /Users/lc/dataCenter/docker/nginx/cert:/etc/nginx/cert
      # 配置文件映射
      - /Users/lc/dataCenter/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      # 页面目录
      - /Users/lc/dataCenter/docker/nginx/html:/usr/share/nginx/html
      # 日志目录
      - /Users/lc/dataCenter/docker/nginx/log:/var/log/nginx
    privileged: true

#  sentinel:
#    image: crush/crush-sentinel-dashboard:1.6.0
#    container_name: sentinel
#    environment:
#      TZ: Asia/Shanghai
#    ports:
#      - "8718:8718"
#    volumes:
#      # 配置文件
#      - /Users/lc/dataCenter/docker/crush-sentinel-dashboard/logs/:/crush/sentinel-dashboard/logs
#      # skywalking 探针
#      - /Users/lc/dataCenter/docker/skywalking/agent/:/crush/skywalking/agent
#    restart: always

  nacos:
    image: crush/crush-nacos:1.7.0
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    environment:
      TZ: Asia/Shanghai
      JAVA_OPTS: "-Xms256m -Xmx512m"
    volumes:
      # 日志目录 注意集群模式下 日志目录不能一致 需要区分例如 nacos1 nacos2
      - /Users/lc/dataCenter/docker/nacos/logs/:/root/nacos/logs
      # 集群配置文件 集群所有nacos都必须使用此文件
      - /Users/lc/dataCenter/docker/nacos/conf/cluster.conf:/root/nacos/conf/cluster.conf

  crush-gateway:
    image: crush/crush-gateway:1.0.0
    container_name: crush-gateway
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "8080:8080"
    volumes:
      # 配置文件
      - /Users/lc/dataCenter/docker/crush-gateway/logs/:/crush/gateway/logs
      # skywalking 探针
      - /Users/lc/dataCenter/docker/skywalking/agent/:/crush/skywalking/agent
    privileged: true

  crush-chat-server:
    image: crush/crush-chat-server:1.0.0
    container_name: crush-chat-server
    environment:
      # 时区上海
      TZ: Asia/Shanghai
    ports:
      - "9201:9201"
    volumes:
      # 配置文件
      - /Users/lc/dataCenter/docker/crush-chat-server/logs/:/crush/chat/server/logs
      # skywalking 探针
      - /Users/lc/dataCenter/docker/skywalking/agent/:/crush/skywalking/agent
    privileged: true

    #################################################################################################
    #################################### 以下为扩展根据需求搭建 #########################################
    #################################################################################################

  elasticsearch:
    image: elasticsearch:7.17.6
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      # 设置集群名称
      cluster.name: elasticsearch
      # 以单一节点模式启动
      discovery.type: single-node
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - /Users/lc/dataCenter/docker/elk/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - /Users/lc/dataCenter/docker/elk/elasticsearch/data:/usr/share/elasticsearch/data
      - /Users/lc/dataCenter/docker/elk/elasticsearch/logs:/usr/share/elasticsearch/logs

  kibana:
    image: kibana:7.17.6
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      # kibana在elasticsearch启动之后再启动
      - elasticsearch
    environment:
      #设置系统语言文中文
      I18N_LOCALE: zh-CN
      # 访问域名
      # SERVER_PUBLICBASEURL: https://kibana.cloud.com
    volumes:
      - /Users/lc/dataCenter/docker/elk/kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml

  logstash:
    image: logstash:7.17.6
    container_name: logstash
    ports:
      - "4560:4560"
    volumes:
      - /Users/lc/dataCenter/docker/elk/logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - /Users/lc/dataCenter/docker/elk/logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    depends_on:
      - elasticsearch

  sky-oap:
    image: apache/skywalking-oap-server:9.3.0
    container_name: sky-oap
    ports:
      - "11800:11800"
      - "12800:12800"
    environment:
      JAVA_OPTS: -Xms1G -Xmx2G
      #记录数据的有效期，单位天
      SW_CORE_RECORD_DATA_TTL: 7
      #分析指标数据的有效期，单位天
      SW_CORE_METRICS_DATA_TTL: 7
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: 127.0.0.1:9200
      TZ: Asia/Shanghai

  sky-ui:
    image: apache/skywalking-ui:9.3.0
    container_name: sky-ui
    ports:
      - "18080:18080"
    environment:
      SW_SERVER_PORT: 18080
      SW_OAP_ADDRESS: http://127.0.0.1:12800
      TZ: Asia/Shanghai
    depends_on:
      - sky-oap

  prometheus:
    image: prom/prometheus:v2.40.1
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - /Users/lc/dataCenter/docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:9.2.4
    container_name: grafana
    environment:
      TZ: Asia/Shanghai
      # 服务地址 用于指定外网ip或域名
      GF_SERVER_ROOT_URL: ""
      # admin 管理员密码
      GF_SECURITY_ADMIN_PASSWORD: 123456
    ports:
      - "3000:3000"
    volumes:
      - /Users/lc/dataCenter/docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /Users/lc/dataCenter/docker/grafana:/var/lib/grafana